package com.accounting.daogen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.accounting.entity.CompanyEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COMPANY_ENTITY".
*/
public class CompanyEntityDao extends AbstractDao<CompanyEntity, Long> {

    public static final String TABLENAME = "COMPANY_ENTITY";

    /**
     * Properties of entity CompanyEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "name");
        public final static Property Address = new Property(2, String.class, "address", false, "address");
        public final static Property Telephone = new Property(3, String.class, "telephone", false, "telephone");
        public final static Property ComplaintTel = new Property(4, String.class, "complaintTel", false, "complaintTel");
        public final static Property Fax = new Property(5, String.class, "fax", false, "fax");
        public final static Property Email = new Property(6, String.class, "email", false, "email");
        public final static Property ExplainTxt = new Property(7, String.class, "explainTxt", false, "explainTxt");
    }


    public CompanyEntityDao(DaoConfig config) {
        super(config);
    }
    
    public CompanyEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COMPANY_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"name\" TEXT UNIQUE ," + // 1: name
                "\"address\" TEXT," + // 2: address
                "\"telephone\" TEXT," + // 3: telephone
                "\"complaintTel\" TEXT," + // 4: complaintTel
                "\"fax\" TEXT," + // 5: fax
                "\"email\" TEXT," + // 6: email
                "\"explainTxt\" TEXT);"); // 7: explainTxt
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COMPANY_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CompanyEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(3, address);
        }
 
        String telephone = entity.getTelephone();
        if (telephone != null) {
            stmt.bindString(4, telephone);
        }
 
        String complaintTel = entity.getComplaintTel();
        if (complaintTel != null) {
            stmt.bindString(5, complaintTel);
        }
 
        String fax = entity.getFax();
        if (fax != null) {
            stmt.bindString(6, fax);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(7, email);
        }
 
        String explainTxt = entity.getExplainTxt();
        if (explainTxt != null) {
            stmt.bindString(8, explainTxt);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CompanyEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(3, address);
        }
 
        String telephone = entity.getTelephone();
        if (telephone != null) {
            stmt.bindString(4, telephone);
        }
 
        String complaintTel = entity.getComplaintTel();
        if (complaintTel != null) {
            stmt.bindString(5, complaintTel);
        }
 
        String fax = entity.getFax();
        if (fax != null) {
            stmt.bindString(6, fax);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(7, email);
        }
 
        String explainTxt = entity.getExplainTxt();
        if (explainTxt != null) {
            stmt.bindString(8, explainTxt);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CompanyEntity readEntity(Cursor cursor, int offset) {
        CompanyEntity entity = new CompanyEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // address
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // telephone
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // complaintTel
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // fax
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // email
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // explainTxt
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CompanyEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAddress(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTelephone(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setComplaintTel(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFax(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setEmail(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setExplainTxt(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CompanyEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CompanyEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CompanyEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
