package com.accounting.daogen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.accounting.entity.BillEntity;
import com.accounting.entity.CompanyEntity;
import com.accounting.entity.CustomerEntity;

import com.accounting.daogen.BillEntityDao;
import com.accounting.daogen.CompanyEntityDao;
import com.accounting.daogen.CustomerEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig billEntityDaoConfig;
    private final DaoConfig companyEntityDaoConfig;
    private final DaoConfig customerEntityDaoConfig;

    private final BillEntityDao billEntityDao;
    private final CompanyEntityDao companyEntityDao;
    private final CustomerEntityDao customerEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        billEntityDaoConfig = daoConfigMap.get(BillEntityDao.class).clone();
        billEntityDaoConfig.initIdentityScope(type);

        companyEntityDaoConfig = daoConfigMap.get(CompanyEntityDao.class).clone();
        companyEntityDaoConfig.initIdentityScope(type);

        customerEntityDaoConfig = daoConfigMap.get(CustomerEntityDao.class).clone();
        customerEntityDaoConfig.initIdentityScope(type);

        billEntityDao = new BillEntityDao(billEntityDaoConfig, this);
        companyEntityDao = new CompanyEntityDao(companyEntityDaoConfig, this);
        customerEntityDao = new CustomerEntityDao(customerEntityDaoConfig, this);

        registerDao(BillEntity.class, billEntityDao);
        registerDao(CompanyEntity.class, companyEntityDao);
        registerDao(CustomerEntity.class, customerEntityDao);
    }
    
    public void clear() {
        billEntityDaoConfig.clearIdentityScope();
        companyEntityDaoConfig.clearIdentityScope();
        customerEntityDaoConfig.clearIdentityScope();
    }

    public BillEntityDao getBillEntityDao() {
        return billEntityDao;
    }

    public CompanyEntityDao getCompanyEntityDao() {
        return companyEntityDao;
    }

    public CustomerEntityDao getCustomerEntityDao() {
        return customerEntityDao;
    }

}
